### ISSUE TITLE
Bitslice Gate Complexity

### ISSUE THREAD

**Issue by savasturk** [peigen-sboxes/PEIGEN#11]
How can I get the 'Bit Slice Gate Complexity' results of a set of S-boxes with using PEIGEN implementation?

**Comment by FreeDisciplina** [comment]
Suppose one wants to get the 'Bit Slice Gate Complexity' results of a set of 4-bit S-boxes:

1. Write the `name` and `Truth table` of the 4-bit S-boxes in the file named `sboxes4.txt`. In the existing file named [sboxes4.txt](https://github.com/peigen-sboxes/PEIGEN/blob/master/sboxes4.txt) there are some examples of S-boxes.
2. compile the program with command: `make search_GC_n4`
3. run with command: `./search_GC_n4 -v -c 6 -l 6 -p 4 -r 160 --not1 --and2 --andn2 --or2 --xor2 -f software.conf`
4. once one gets the results, one has to manually remove the intermediate bit-permutations (e.g., by drawing a graph) ([there are some examples of the resulting implementations](https://www.dropbox.com/sh/x6y7u8gfvi0ki72/AAAjiUAHBfwrilMOVhtCCSZsa/EvaluationResults/Sect5.2_ImplementedSboxes/N4_Software?dl=0&subfolder_nav_tracking=1)) and here is [a simple explanation and an example of drawing a graph to get the implementation](https://www.dropbox.com/sh/x6y7u8gfvi0ki72/AABi7bXJx0gpZDisxy9C-R5oa/EvaluationResults/Sect5.2_ImplementedSboxes?dl=0&preview=A_Simple_Explaination.pdf&subfolder_nav_tracking=1).

In the file named [main.cpp](https://github.com/peigen-sboxes/PEIGEN/blob/master/main.cpp), there are some examples.

**Comment by savasturk** [comment]
Thanks, I implemented it but got this result:

Finding BGC/GEC/MC implementations
Precompute Limit : 6
x: invalid option -- 'l'
wrong cmd lineThread number : 4

Why?

**Comment by FreeDisciplina** [comment]
No worries. This "x: invalid option -- 'l' wrong cmd line" does not matter. The program can work correctly.

It is there because in [main.cpp](https://github.com/peigen-sboxes/PEIGEN/blob/master/main.cpp) (due to my laziness), the function `sbox4_GC.pre_compute` uses the same `args` with the function `sbox4_GC.search_batch_concatenate`, while `-l` is not an option in function `pre_compute`.

**Comment by savasturk** [comment]
thanks, it solved
