### ISSUE TITLE
Icepole, 5-bit s-box algebraic degree

### ISSUE THREAD

**Issue by savasturk** [peigen-sboxes/PEIGEN#13]
Hello, I calculated Icepole's Algebraic Normal Forms for each output boolean functions like this:

y0 =  x0*x1*x2*x3 + x0*x1*x2*x4 + x0*x1*x2 + x0*x1*x3*x4 + x0*x1*x3 + x0*x1*x4 + x0*x1 + x0*x2*x3*x4 + x0*x2*x3 + x0*x2*x4 + x0*x2 + x0*x3*x4 + x0*x3 + x0*x4 + x1*x2*x3*x4 + x1*x2*x3 + x1*x2*x4 + x1*x2 + x1*x3*x4 + x1*x3 + x1*x4 + x1 + x2*x3*x4 + x2*x3 + x2*x4 + x2 + x4 + 1

y1 =  x0*x1*x2*x3 + x0*x1*x2*x4 + x0*x1*x2 + x0*x1*x3*x4 + x0*x1*x3 + x0*x1*x4 + x0*x1 + x0*x2*x3*x4 + x0*x2*x3 + x0*x2*x4 + x0*x2 + x0*x3*x4 + x0*x3 + x0 + x1*x2*x3*x4 + x1*x2*x3 + x1*x2*x4 + x1*x2 + x1*x3*x4 + x1*x3 + x1*x4 + x2*x3*x4 + x2*x3 + x2*x4 + x2 + x3*x4 + x3 + 1

y2 =  x0*x1*x2*x3 + x0*x1*x2*x4 + x0*x1*x2 + x0*x1*x3*x4 + x0*x1*x3 + x0*x1*x4 + x0*x2*x3*x4 + x0*x2*x3 + x0*x2*x4 + x0*x2 + x0*x3*x4 + x0*x3 + x0*x4 + x1*x2*x3*x4 + x1*x2*x3 + x1*x2*x4 + x1*x2 + x1*x3*x4 + x1*x3 + x1*x4 + x1 + x2*x3*x4 + x2*x3 + x2*x4 + x3*x4 + x3 + x4 + 1

y3 =  x0*x1*x2*x3 + x0*x1*x2*x4 + x0*x1*x2 + x0*x1*x3*x4 + x0*x1*x3 + x0*x1*x4 + x0*x1 + x0*x2*x3*x4 + x0*x2*x3 + x0*x2*x4 + x0*x2 + x0*x3*x4 + x0*x3 + x0*x4 + x0 + x1*x2*x3*x4 + x1*x2*x3 + x1*x2*x4 + x1*x3*x4 + x1*x3 + x1*x4 + x2*x3*x4 + x2*x3 + x2*x4 + x2 + x3*x4 + x4 + 1

y4 =  x0*x1*x2*x3 + x0*x1*x2*x4 + x0*x1*x2 + x0*x1*x3*x4 + x0*x1*x3 + x0*x1*x4 + x0*x1 + x0*x2*x3*x4 + x0*x2*x3 + x0*x2*x4 + x0*x2 + x0*x3*x4 + x0*x3 + x0*x4 + x0 + x1*x2*x3*x4 + x1*x2*x3 + x1*x2*x4 + x1*x2 + x1*x3*x4 + x1*x3 + x1*x4 + x1 + x2*x3*x4 + x2*x4 + x3*x4 + x3 + 1

Accordint to each normal form; each of them degree is 4. Because of this Icepole 5-bit Sbox's algebraic degree(min degree = your result column) must be 4. Your results in 'EVA' directory ''properties_sboxes5_Part0.csv" file "min_degree" column give me 2 result. How can you calculate 2 result, it cause conflit accordint to ANF of Icepole. Could you explain this conflict, please?

**Comment by FreeDisciplina** [comment]
The minimum degree of an Sbox is defined as the minimum degrees among its **components**, which are linear combinations of its **coordinates**, rather than its **coordinates** themselves. In the [file](https://github.com/peigen-sboxes/PEIGEN/blob/master/EvaluationResults/Sect5.1_CryptographicProperties/Sboxes5/properties_icepole.txt) showing the detailed properties of Icepole Sbox, one could find the ANFs of its components. From this file, one will find that some of its components are of degree 2.

**Comment by savasturk** [comment]
How can I calculate linear combinations of its coordinates?

**Comment by savasturk** [comment]
Thanks, I understood.
