### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by ShahinGh** [peigen-sboxes/PEIGEN#7]
Hello, I want to run the code but I've got so many errors.
I'm compiling with Dev-C++ 5.1.1. 
It would be great to tell us how to compile & build and run? 
I can write my weird errors if you want to.
Thanks in advance.

**Comment by pfasante** [comment]
Using g++ 9.2.1 on my linux machine, the following works:

    % cat test.cpp
    #include <iostream>
    #include "func.hpp"

    using namespace Peigen;
    using std::cout;
    using std::endl;

    int main(int argc, char** argv) {
        auto SboxLUTstr = "0c05060b09000a0d030e0f0804070102";
        Peigen::function_t<4> S(SboxLUTstr);
        cout << "ANF: " << S.show_coordinates_ANF() << endl;
        cout << "DDT: " << S.show_difference_distribution_matrix() << endl;
    }

Now compiling the file needs `-march=native` option:

    % g++ -o test test.cpp -O3 -Wall -march=native
    % ./test
    ANF: ANF of coordinates:
    y0 = 1 + x0 +    + x2 + x3 +      +      + x1x2 +      +      +      +        +        +        +       ;    deg = 2, term_n =  5, related_n = 4
    y1 = 1 +    + x1 +    + x3 +      +      +      +      + x1x3 + x2x3 + x0x1x2 + x0x1x3 + x0x2x3 +       ;    deg = 3, term_n =  8, related_n = 4
    y2 =   +    +    + x2 + x3 + x0x1 +      +      + x0x3 + x1x3 +      +        + x0x1x3 + x0x2x3 +       ;    deg = 3, term_n =  7, related_n = 4
    y3 =   + x0 + x1 +    + x3 +      +      + x1x2 +      +      +      + x0x1x2 + x0x1x3 + x0x2x3 +       ;    deg = 3, term_n =  7, related_n = 4
    
    DDT: DDT =
    {
          0|   1|   2|   4|   8|   3|   5|   6|   9|   a|   c|   7|   b|   d|   e|   f|
    {0:  16,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, },
    {1:   0,   0,   0,   0,   0,   4,   0,   0,   4,   0,   0,   4,   0,   4,   0,   0, },
    {2:   0,   0,   0,   0,   0,   2,   4,   2,   0,   2,   2,   0,   0,   2,   2,   0, },
    {4:   0,   0,   0,   0,   0,   0,   4,   2,   2,   2,   2,   2,   0,   0,   2,   0, },
    {8:   0,   0,   0,   0,   0,   2,   0,   0,   2,   0,   0,   2,   4,   2,   0,   4, },
    {3:   0,   2,   0,   2,   0,   2,   0,   4,   0,   2,   0,   2,   2,   0,   0,   0, },
    {5:   0,   2,   0,   2,   0,   0,   0,   0,   2,   2,   4,   0,   2,   2,   0,   0, },
    {6:   0,   0,   2,   0,   2,   0,   0,   2,   0,   0,   2,   0,   4,   0,   0,   4, },
    {9:   0,   0,   2,   4,   2,   0,   0,   2,   0,   0,   2,   0,   0,   0,   4,   0, },
    {a:   0,   0,   2,   0,   2,   2,   4,   0,   0,   2,   0,   0,   0,   2,   2,   0, },
    {c:   0,   0,   2,   0,   2,   0,   4,   0,   2,   2,   0,   2,   0,   0,   2,   0, },
    {7:   0,   4,   2,   0,   2,   0,   0,   2,   0,   0,   2,   0,   0,   0,   0,   4, },
    {b:   0,   2,   0,   2,   4,   0,   0,   0,   2,   2,   0,   0,   2,   2,   0,   0, },
    {d:   0,   2,   4,   2,   0,   2,   0,   0,   0,   2,   0,   2,   2,   0,   0,   0, },
    {e:   0,   0,   2,   0,   2,   2,   0,   2,   2,   0,   2,   2,   0,   2,   0,   0, },
    {f:   0,   4,   0,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   4,   4, },
    };
    Diff: 4, DDT_spectrum: {0:159, 2:72, 4:24, 16:1, };
    Diff1: 0, DDT1_spectrum: {0:16, };

Hope this helps - if not, it might be helpful to provide us your code.

**Comment by ShahinGh** [comment]
@pfasante Thanks for your feedback, would you explain the process from the start? I'm doing these:
1.first I download the project 
2. change directory to the downloaded folder.
3. run "cat > test.cpp"
4. then write the code you wrote into test.cpp
5. run "g++ -o test test.cpp -O3 -Wall -march=native "
The output result is : 

https://ibb.co/1zzP28D


Please correct any step that is wrong above. 
Thanks in advance dear.

**Comment by pfasante** [comment]
Your approach sounds correct. However, I cannot see any errors in the output, but that seems to be also cutoff and only shows the first part of the output? Maybe you can paste the output text instead to a pastebin site?

To compile the peigen src without errors, I also had to do some changes (maybe due to a newer gcc version, but not sure), see the following diff:

```
diff --git a/constants.hpp b/constants.hpp
index 02ab0e2..f9f1d07 100644
--- a/constants.hpp
+++ b/constants.hpp
@@ -327,7 +327,7 @@ const __m128i S4_coors_deg_mask2 = _mm_set_epi64x(0x0ULL, 0x1668166816681668ULL)
 const __m128i S4_coors_deg_mask1 = _mm_set_epi64x(0x0ULL, 0x0116011601160116ULL); // 0000 0001 0001 0110

 template<int N>
-const array<int, N+1> HWorder_off = [&]
+const array<int, N+1> HWorder_off = []
 {
   array<int, N+1> aHWorder_off;
   aHWorder_off[0] = 0;
@@ -339,7 +339,7 @@ const array<int, N+1> HWorder_off = [&]
 }();

 template<int N>
-const array<int, 1<<N> HWorder = [&]
+const array<int, 1<<N> HWorder = []
 {
   array<int, 1<<N> aHWorder;
   int offset[N + 1] = { 0 };
@@ -1089,7 +1089,7 @@ template<int N>
 const Perm_t<N> PE;

 template<int N>
-const array<Peigen::function_t<N>, (1<<N)> XE = [&]
+const array<Peigen::function_t<N>, (1<<N)> XE = []
 {
   Peigen::function_t<N> I = Peigen::function_t<N>::INPUT_DEFAULT();
   array<Peigen::function_t<N>, (1<<N)> aXE;
@@ -1106,7 +1106,7 @@ const array<Peigen::function_t<N>, (1<<N)> XE = [&]
 }();

 template<int N>
-const bit_slice_t<N> masks = [&]
+const bit_slice_t<N> masks = []
 {
   bit_slice_t<N> amask;
   bit_slice_l_t<N> mask_init;
@@ -1136,7 +1136,7 @@ struct LExinfoGx_t
 };

 template<int N>
-const map<array<uint8_t, LUT_UNIT_N>, LExinfoGx_t<N> > G_Rs = [&]
+const map<array<uint8_t, LUT_UNIT_N>, LExinfoGx_t<N> > G_Rs = []
 {
   map<array<uint8_t, LUT_UNIT_N>, LExinfoGx_t<N> > aG_Rs;
   if (N == 4)
```

and

```
diff --git a/subspaces.hpp b/subspaces.hpp
index c78cf46..4f08d14 100644
--- a/subspaces.hpp
+++ b/subspaces.hpp
@@ -51,7 +51,7 @@ using namespace std;
   according to the method used in sagemath reduced_echelon_matrix_iterator() method
 */
 template<int N>
-const vector<vector<vector<uint8_t> > > SubSpaces = [&]
+const vector<vector<vector<uint8_t> > > SubSpaces = []
 {
     if (N <= 8)
     {
```

This basically changes all `[&]` captures from global lambda functions to `[]`.
Again: I don't know the exact error, I just did what my compiler told me.

**Comment by FreeDisciplina** [comment]
Thank Friedrich very much for the help.

@ShahinGh There are some examples in [main.cpp](https://github.com/peigen-sboxes/PEIGEN/blob/master/main.cpp), one can use the [Makefile](https://github.com/peigen-sboxes/PEIGEN/blob/master/Makefile) and build the executable code for the examples (as explained in the [Usage](https://github.com/peigen-sboxes/PEIGEN#usage) in the README).

One can use the following as the compile option:
`-fopenmp -mavx2 -std=c++14 -O3 -Wall -Wextra -pedantic`

Sorry for the tremendous warnings.
To ignore the warnings, one possible method is to add the following to the source file containing the main function (e.g., the [main.cpp](https://github.com/peigen-sboxes/PEIGEN/blob/master/main.cpp) in this project that includes some examples, and the `test.cpp` provided by Friedrich):

    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-parameter"
    #pragma GCC diagnostic ignored "-Wsign-compare"
    #pragma GCC diagnostic ignored "-Wunused-variable"
    #pragma GCC diagnostic ignored "-Woverflow"
    #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"

    #include "faster.hpp"
    #include "func.hpp"
    #include "evaluator.hpp"
    #include "lighter.hpp"

    #pragma GCC diagnostic pop

**Comment by FreeDisciplina** [comment]
@ShahinGh @pfasante 
Besides, apologize very much for that there is a bug in computing the ANF for 3-bit and 4-bit S-boxes.

This has been correct just now.
Sorry for the inconvenient that brought.

**Comment by ShahinGh** [comment]
@pfasante  @FreeDisciplina Thank you so much, it solved my problem.
