### ISSUE TITLE
How to use generation and implementation?

### ISSUE THREAD

**Issue by ali13711992** [peigen-sboxes/PEIGEN#8]
Hello!
I have trouble to run the code for generation and implementation features.
I am beginner to programming.(Sorry about that)
i have successfully run the code for Evaluation but i cant get output for generation and implementation feature.
I read the readme file and do what you said (adding namespaces and #includes) but fail and compiler outputs a file named a.out
please provide an example to run the code.
I am using g++ on ubonto 18 64-bit

**Comment by FreeDisciplina** [comment]
Hi,

In `main.cpp`, there are some examples, which can be built use the `Makefile`.

For example, for implementation:

One can use the command `make search_GC_n3` to build the example of finding implementations in terms of BGC/GEC/MC for *3*-bit S-boxes.

 - that will generate an executable file named `search_GC_n3`
 - the default argument is `-v -c 6 -l 6 -p 4 -r 160 --not1 --and2 --andn2 --or2 --xor2 -f software.conf`, which can find implementation using `not1`, `and2`, `andn2`, `or2`, `xor2` instructions. The cost of each instruction is defined in the file named `software.conf` (one can change it to specify the cost of each instructions as one's will).
 - the default file that contains the name of the S-boxes and the specification of the S-boxes to be implemented is named `sboxes3.txt` (one can replace it by adding `-o xx` to the arguments, where `xx` is the file name that contains the name of the S-boxes and the specification of the S-boxes to be implemented).
 - one can also run the generated executable file `search_GC_n3` with non-default argument that is similar to the default one. E.g., one can use the command
    `search_GC_n3 -av -c 7 -l 7 -p 4 -r 160 -o sboxes3.txt -f TSMC65nm.conf`.
 - the meaning of the options in the argument are explained in `README` (section Usage).

That also applies to *4*-bit S-boxes.

For writing a source file that includes the headers, contains a main function, initiates objects, and calls the functions, one can see the following part in the `main.cpp`:

> #include "faster.hpp"
> #include "func.hpp"
> #include "evaluator.hpp"
> #include "lighter.hpp"
> 
> using namespace std;
> using namespace Peigen;
> using namespace Peigen::depth;
> using namespace Peigen::weight;
> ...
>  #if defined(GC)
>        cout << "Finding BGC/GEC/MC implementations" << endl;
>  #if(SIZEINBIT == 3)
>  ...
>  #endif
>  #endif
>  ...
> #if defined(GEN)
>       cout << "Generating " << endl;
> #if(SIZEINBIT == 3)
>  ...
>  #endif
>  #endif

And the following part in the `Makefile`:
> CC=g++ -fopenmp
> CFLAGS= -mavx2 -std=c++14 -O3 -Wall -Wextra -pedantic
> LDFLAGS=
> EXEC= search_GC_n3 search_GC_n4  gen_n3 gen_n4
> 
> search_GC_n3: search_GC_n3.o
> 	$(CC) -o $@ $^ $(LDFLAGS) -DGC -DSIZEINBIT=3
> 
> search_GC_n3.o: main.cpp
> 	$(CC) -o $@ -c $< $(CFLAGS) -DGC -DSIZEINBIT=3
> 
> search_GC_n4: search_GC_n4.o
> 	$(CC) -o $@ $^ $(LDFLAGS) -DGC -DSIZEINBIT=4
> 
> search_GC_n4.o: main.cpp
> 	$(CC) -o $@ -c $< $(CFLAGS) -DGC -DSIZEINBIT=4
> 
> ...
> gen_n3: gen_n3.o
> 	$(CC) -o $@ $^ $(LDFLAGS) -DGEN -DSIZEINBIT=3
> 
> gen_n3.o: main.cpp
> 	$(CC) -o $@ -c $< $(CFLAGS) -DGEN -DSIZEINBIT=3
> 
> gen_n4: gen_n4.o
> 	$(CC) -o $@ $^ $(LDFLAGS) -DGEN -DSIZEINBIT=4
> 
> gen_n4.o: main.cpp
> 	$(CC) -o $@ -c $< $(CFLAGS) -DGEN -DSIZEINBIT=4

And refer to the `Usage` section in `README`:
> - To find efficient implemtations in terms of BGC/GEC/MC:
> ...
> - To generate S-boxes fulfilling given criteria
> ...
> - To build the demo program in `main.cpp`

Note that, there are some notes in the `main.cpp` warns that the memory requirements for finding implementations and generations of 4-bit S-boxes are very large. Finding the implementations as good as possible,  we ran them with larger limitations (i.e., the options `-l` and `-c`) in a server with 128 GB memory. To run as a demon on a PC, we recommend setting them smaller.

The note in the `main.cpp` is quoted here:
>  Here, the limit (-c) for pre-compute and the limit (-l) for finding implementations
>  are set to be a little bit smaller than that set to get the results in the paper.
>  In the paper, -c and -l for software is set to be 7, for TSMC65nm and UMC180nm they are set to be 12.
>  That will cost reletively longer time and large memory.
>  So, to run as a demon on a PC, we recommend to set them smaller
>  and set them larger to find better solutions when running on a server
>  The following settings for ``generation'' are similiar.

**Comment by ali13711992** [comment]
i have generated all of the files in main.cpp but i cant execute them. when i try to run the result i give this error
root@ali-VirtualBox:~/Desktop/shared# ./gen_n3
Generating ---> its look likes the system is trying to run the code 
Illegal instruction (core dumped) --> here is the error
or
ali@ali-VirtualBox:~/Desktop/shared$ ./search_GC_n4 software.conf
Finding BGC/GEC/MC implementations
Illegal instruction (core dumped)

here is my g++ info
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

here is my linux os info
i run this os on virtualbox
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by ali13711992** [comment]
i have try to evaluate some examples too
here is my example named b.cpp

#include "func.hpp"
#include "lighter.hpp"

using namespace std;
using namespace Peigen;
using namespace Peigen::depth;
using namespace Peigen::weight;

int main(int argc, char** argv)
{
	cout << "Evaluating Cryptographic Properties" << endl;
	Peigen::weight::lighter<3> sbox3_Eva;
	sbox3_Eva.omp_nb_threads = 1;
	sbox3_Eva.evaluate("sboxes3.txt", "properties_sboxes3_2.csv");
	sbox3_Eva.evaluate_verbose("sboxes3.txt", "properties");
}

i run it using "g++ -o b b.cpp -O3 -Wall -march=native
but no output generated. here is the log file
[1.txt](https://github.com/peigen-sboxes/PEIGEN/files/4424328/1.txt)

also 
when i try to gencheck all of the resualt files are empty

**Comment by FreeDisciplina** [comment]
I am so sorry. Your command `./search_GC_n4 software.conf` cannot be understood by PEIGEN.

He understands commands like that:
    `./search_GC_n4 -v -c 6 -l 6 -p 4 -r 160 --not1 --and2 --andn2 --or2 --xor2 -f software.conf`
or
    `./search_GC_n4 -av -c 9 -l 9 -p 4 -r 160 -f TSMC65nm.conf`
or
    `./search_GC_n4 -v -c 9 -l 9 -p 4 -r 160 --not1 --nand2 --nor2 --and2 --or2 --xor2 --xnor2 --andn2 --orn2 --nand3 --nor3 --maoi1 --moai1 -f UMC180nm.conf`

You can add `-o mysboxes4.txt`, which contains the name of the S-boxes and the specification of the S-boxes to be implemented, to the argument list.

By the way, please use `-f` before the `software.conf` for PEIGEN to recognize the file `software.conf`.

For successfully sent command to PEIGEN, and be happy that PEIGEN works as what you commanded it, please listen what he has said in `README`.

----
For compiling, add `-std=c++14` may solve the problem.
The `Makefile` contains the complete flags needed for compiling.

**Comment by ali13711992** [comment]
thanks for your answer
i have already read the readme file. and do what is it said before i opened this issue. but no result

> ./search_GC_n4 -v -c 6 -l 6 -p 4 -r 160 --not1 --and2 --andn2 --or2 --xor2 -f software.conf 

i tried above command you said exactly before but problem not solved.
also i have added -std=c++14 on top of the makefile but no changes. and all of the created files (testcode.cpp, results_correct.txt and results.c) are empty. i generated gen_n4 before and put the files in a subfolder named R
here is the log files:
ali@ali-VirtualBox:~/Desktop/shared$ make gencheck
find ./R -maxdepth 1 -name "*.c" -print > results.c
g++ -fopenmp -mavx2 -std=c++14 -O3 -Wall -Wextra -pedantic genTest.cpp -o genTest && ./genTest
ali@ali-VirtualBox:~/Desktop/shared$ 


[make search_GC_n4.txt](https://github.com/peigen-sboxes/PEIGEN/files/4425804/make.search_GC_n4.txt)
and here is the result of your command

ali@ali-VirtualBox:~/Desktop/shared$ ./search_GC_n4 -v -c 6 -l 6 -p 4 -r 160 --not1 --and2 --andn2 --or2 --xor2 -f software.conf
Finding BGC/GEC/MC implementations
Illegal instruction (core dumped)
i have provided 4 cpu cores and tested again bot no success 
sorry for wasting your time
Thnaks

**Comment by FreeDisciplina** [comment]
Hi,

From `make.search_GC_n4.txt`, we can see the compiling has finished.
There is no error, only tons of warnings. I guess the `search_GC_n4` has already generated.

We apologize very much for those tons of warnings. Please ignore those warnings.
To block the warnings, one can add the following to the source file containing the main function (e.g., the main.cpp in this project that includes some examples) like this:

    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-parameter"
    #pragma GCC diagnostic ignored "-Wsign-compare"
    #pragma GCC diagnostic ignored "-Wunused-variable"
    #pragma GCC diagnostic ignored "-Woverflow"
    #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
    
    #include "faster.hpp"
    #include "func.hpp"
    #include "evaluator.hpp"
    #include "lighter.hpp"
    
    #pragma GCC diagnostic pop

For the runtime error, on my laptop, it runs like that:

    $./search_GC_n3 -v -c 6 -l 6 -p 4 -r 160 --not1 --and2 --andn2 --or2 --xor2 -f software.conf
    Finding BGC/GEC/MC implementations
    Precompute Limit : 6
    x: invalid option -- 'l'
    wrong cmd lineThread number : 4
    0
    1
    2
    ...
    599
    600
    Pre-computation takes time (mins): 0.00598958
    Precomputed Limit : 6
    Lambda : 6
    Thread number : 4
    
    f1_succ : 0 (1) 100 (9) 200 (57) 300 (211) 400 (483) 500 (1146) 600 (1662) 700 (2149) 800 (754) 
    Total = 6472
    f2_succ : 
    Total = 0
    From : f0_cc_aa
    To   : 78_9c_56
    0
    100
    Generating implementation PRINTcipher 0
    (cost : 400 + 200 -> 6GE)
    200
    300
    Best : 6.000000 GE
    Takes time (mins): 0.0015625
    From : f0_cc_aa
    To   : 1e_ac_6a
    0
    100
    Generating implementation SEA 0
    (cost : 400 + 200 -> 6GE)
    200
    300
    Best : 6.000000 GE
    Takes time (mins): 0.00078125
    From : f0_cc_aa
    To   : 2b_93_e1
    0
    100
    200
    Generating implementation ctc2 0
    (cost : 500 + 300 -> 8GE)
    300
    Generating implementation ctc2 1
    (cost : 300 + 400 -> 7GE)
    400
    Best : 7.000000 GE
    Takes time (mins): 0.00130208
    From : f0_cc_aa
    To   : 2d_63_59
    100
    200
    Generating implementation ctc2 0
    (cost : 500 + 300 -> 8GE)
    300
    Generating implementation ctc2 1
    (cost : 300 + 400 -> 7GE)
    400
    Best : 7.000000 GE
    Takes time (mins): 0.00130208
    From : f0_cc_aa
    To   : 2d_63_59
    0
    100
    200
    Generating implementation 3-way 0
    (cost : 500 + 300 -> 8GE)
    300
    400
    Best : 8.000000 GE
    Takes time (mins): 0.00104167
    Total time (mins): 0.0125

Here, the `x: invalid option -- 'l'` and `wrong cmd lineThread number : 4` complains do not influence the execution. It arises because I simply share the same argument list for the `pre_compute` and the `search_batch_concatenate` functions. They actually accept sightly different arguments.

After executing this, I can get the implementations (I ran use 3-bit S-boxes).

I guess one possible reason that we got different outputs, is that maybe your computer does not support the `SSE/AVX/POPCNT` instructions.
Another possible reason is that the input file is not encoded as required.

There is a related issue for references.
https://github.com/peigen-sboxes/PEIGEN/issues/1#issuecomment-488679486
https://github.com/peigen-sboxes/PEIGEN/issues/1#issuecomment-492550523

We apologize that we cannot solve that issue also.
If the computer does support those instructions, and the files are encoded as required, we apologize that we cannot figure out other possible reasons.

**Comment by ali13711992** [comment]
Finally I did it.
code is running successfully now. The problem coused by computer hardware performance

**Comment by ali13711992** [comment]
Finally I did it.
code is running successfully now. The problem coused by computer hardware performance. I have just learned by experience that code not running correctly on AMD CPU architecture. code not running correctly on virtual machine (I have used Oracle VirtualBox). code is running correctly on this system config:

Ubuntu 18.04.4 LTS
CPU: Intel® Core™ i5-8400 CPU @ 2.80GHz × 6 
Memory: 16GB

Now, there are 3 question i have:
1- i have run the code to check Affine Equivalence between two sboxes and result was like this:
----------------------Affine Equivent Check Result----------------------
RS: dec0_7b30_6cac_bd0a, 000102030406080a050c0b0f0d070e09
S1_L1: 9696_cccc_ff00_55aa, 00090c050801040d030a0f060b02070e
S1_L2: 33cc_6996_9966_0ff0, 00060e0805030b0d0f0901070a0c0402
S1_c: 9
S2_L1: 6996_3c3c_cccc_ff00, 00080e060c04020a0901070f050d0b03
S2_L2: 3c3c_9966_0ff0_5a5a, 00050c090b0e070206030a0f0d080104
S2_c: 9

may you clearify what is RS, S1_L1, S1_L2, S1_c, S2_L1, S2_L2, S2_c?
2:
I have run the command "make gen_n4" then "./gen_n4 -v -c 6 -l 6 -p 4 -r 160 --not1 --and2 --andn2 --or2 --xor2 -f software.conf -s criteria.conf" results is provided as 2.txt in results.zip attachment. when i run the command computation will be done but results .csv file is empty and only have headers. please tell me how to solve the problem.
3:
I want to save evaluation results for n-bit sboxes in seperate folders for example i want to put results of this code in a Folder named "4-bits_ Sboxes_eva":
t0 = clock();
	Peigen::weight::lighter<4> sbox4_Eva;
	sbox4_Eva.omp_nb_threads = 1;
	sbox4_Eva.evaluate("sboxes4.txt", "properties_sboxes4.csv");
	sbox4_Eva.evaluate_verbose("sboxes4.txt", "properties");
	t1 = clock() - t0;
	cout << "Total time (mins): " << (((double)t1) / (CLOCKS_PER_SEC * 60.0)) << endl;

thank you for your great program and i praise your afforts
[results.zip](https://github.com/peigen-sboxes/PEIGEN/files/5045974/results.zip)
